### PR TITLE
Implement `dtrt-indent-set`

### LINKED ISSUE #82: `dtrt-indent-set`
Hey there, thanks for the great mode!

I'm always wondering what command I need to type to change the indentation offset with the mode I'm on. What would you think of adding a `dtrt-indent-set` command that would prompt for an indentation offset, and work with all modes supported by `dtrt-indent-set` in the first place – thus acting as a central command for indentation?

### PR DESCRIPTION
**Pull request by ramnes**
Closes #82

### CODE REVIEW

**Comment by rrthomas** [comment]
Wow, this is great! Thanks for doing this.

What would you think about having a message if no variable can be found, when the function is called interactively? Would be nice to warn/explain to the user who might otherwise be confused when it has no effect.

**Comment by ramnes** [comment]
Why not, but then ideally we'd want to error before prompting the user for an offset, and I'm not sure how to do that. I'll eventually take a deeper look when I have some time to spare. :)

**Comment by rrthomas** [comment]
I think giving an error is the main thing, so while you're right, I don't think that matters, and I'd rather land the PR sooner; so, I'd be quite happy with just having a message output when there's no setting variable found and the function is called interactively.

**Comment by ramnes** [comment]
@rrthomas done then :)

**Comment by rrthomas** [comment]
Many thanks! New release shortly.

**Pull request merged**
