### PR TITLE
Make generic-mapping-list a defcustom

### LINKED ISSUE #24: Symbol's value as variable is void: evil-mode
This happens when opening any file. Disabling dtrt-indent removes the error. It appears to be related to the reference in https://github.com/jscheid/dtrt-indent/blob/e029624eebe4c85f3b43452fa4456df1019c2d3f/dtrt-indent.el#L335

Is there any way we can get this list made into a `defcustom`? I, and several users I know, load our packages automatically using a package list that will install a package if it doesn't exist and load it on startup, and this means I have to define a global variable at the top of my user-init-file on startup.

### PR DESCRIPTION
**Pull request by andschwa**
This fixes #24. I missed an edge case.

### CODE REVIEW

**Comment by jackcviers** [comment]
I can confirm. It works!

**Comment by andschwa** [comment]
@rrthomas Merge please, I fixed what I broke.

**Comment by rrthomas** [comment]
Thanks for this: I got the error once, but on restarting Emacs it didn't happen again when I next used `dtrt-indent`, so I didn't look closer.

**Comment by jackcviers** [comment]
@rrthomas -- no problem. It was easy to find. I probably should have fixed it myself after I found it, but was knee-deep in something else.

**Comment by andschwa** [comment]
Sorry about the bug, I thought I'd tested that case. Evidently not :/

**Pull request merged**
