### PR TITLE
SGML support

### PR DESCRIPTION
**Pull request by jipodine**
From saturday06, comment fixed.

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks. This needs rebasing on head: it won't currently merge.

**Comment by jipodine** [comment]
Yes. (Still new to git.)

**Comment by rrthomas** [comment]
Thanks very much, @jipodine, for both the encouragement and work on getting dtrt-indent updated recently.

**Comment by jipodine** [comment]
Happy to see it back on melpa :)

**Pull request merged**
